name: Test
"on":
  workflow_dispatch:
  pull_request:
    branches:
      - "spec-**"
  push:
    branches:
      - "spec-**"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yamllint
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: adrienverge/yamllint
          tag: v1.37.1
          cache: enable

      - name: Lint schemes
        run: yamllint ${{ github.workspace }} && ${{ github.workspace }}/scripts/lint "${{ github.workspace }}"
